export type appBuildVersionType = {
  version: string;
  link: string;
};

export type AppType = {
  id: string;
  name: string;
  queryName?: string;
  iosAppId?: string;
  androidAppId?: string;
  serviceStatus?: string;
  env: string;
  tenant: string;
  city: string;
  country: string;
  region: string;
  iosVersion?: string;
  iosLink?: string;
  iosRelease?: string;
  iosFolder?: string;
  iosBundleId?: string;
  iosBuilds?: appBuildVersionType[];
  iosScreenshots?: string[];
  iosCurrentVersionReleaseDate?: string;
  androidVersion?: string;
  androidRelease?: string;
  androidFolder?: string;
  androidLink?: string;
  androidBuilds?: appBuildVersionType[];
  androidScreenshots?: string[];
  androidCurrentVersionReleaseDate?: string;
  languages?: string[];
  colorSpecs?: string;
  figmaAppName?: string;
  webAppFigmaLink?: string;
  webAppLink?: string;
  lastStoreUpdate?: number;
  imageUrl?: string;
  pso?: string;
  psm?: string;
};
