name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Print working directory
      run: pwd

    - name: List root directory
      run: ls -R

    - name: Backup logs directory
      run: |
        mkdir -p ../backup
        if [ -d "logs" ]; then
          cp -r logs ../backup/
        fi

    - name: List backup directory
      run: ls -R ../backup

    - run: npm ci

    - run: npm run build

    - name: Set up environment variables
      run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - name: List directory before restore
      run: ls -R

    - name: Restore logs directory
      run: |
        if [ -d "../backup/logs" ]; then
          cp -r ../backup/logs .
        fi

    - name: List restored logs directory
      run: ls -R logs

    - name: Restart PM2
      run: |
        pm2 restart dist/server.js
